{
    "name": "Business Overview Dashboard",
    "version": "19.0.3.0.0",
    "summary": "Overview dashboards — Sales, Purchase, and Inventory",
    "category": "Sales",
    "author": "DLHM",
    "license": "LGPL-3",
    "sequence": 1,
    "depends": ["base", "web", "sale_management", "purchase", "stock"],
    "data": [
        "security/ir.model.access.csv",
        "views/sales_overview_action.xml",
        "views/purchase_overview_action.xml",
        "views/inventory_overview_action.xml",
        "views/menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "odoo_overview_dashboard/static/src/js/overview/overview_constants.js",
            "odoo_overview_dashboard/static/src/js/overview/overview_data_sales.js",
            "odoo_overview_dashboard/static/src/js/overview/overview_data_purchase.js",
            "odoo_overview_dashboard/static/src/js/overview/overview_data_inventory.js",
            "odoo_overview_dashboard/static/src/js/overview/overview_formatters.js",
            "odoo_overview_dashboard/static/src/xml/overview_nav_item.xml",
            "odoo_overview_dashboard/static/src/js/overview/overview_nav_item.js",
            "odoo_overview_dashboard/static/src/xml/overview_sidebar.xml",
            "odoo_overview_dashboard/static/src/js/overview/overview_sidebar.js",
            "odoo_overview_dashboard/static/src/xml/overview_panel.xml",
            "odoo_overview_dashboard/static/src/js/overview/overview_panel.js",
            "odoo_overview_dashboard/static/src/xml/overview_section_header.xml",
            "odoo_overview_dashboard/static/src/js/overview/overview_section_header.js",
            "odoo_overview_dashboard/static/src/xml/overview_kpi_card.xml",
            "odoo_overview_dashboard/static/src/js/overview/overview_kpi_card.js",
            "odoo_overview_dashboard/static/src/xml/overview_ranked_table.xml",
            "odoo_overview_dashboard/static/src/js/overview/overview_ranked_table.js",
            "odoo_overview_dashboard/static/src/xml/overview_dashboard_hero.xml",
            "odoo_overview_dashboard/static/src/js/overview/overview_dashboard_hero.js",
            "odoo_overview_dashboard/static/src/xml/overview_dashboard_skeleton.xml",
            "odoo_overview_dashboard/static/src/js/overview/overview_dashboard_skeleton.js",
            "odoo_overview_dashboard/static/src/xml/sales_dashboard_body.xml",
            "odoo_overview_dashboard/static/src/js/overview/sales_dashboard_body.js",
            "odoo_overview_dashboard/static/src/xml/purchase_dashboard_body.xml",
            "odoo_overview_dashboard/static/src/js/overview/purchase_dashboard_body.js",
            "odoo_overview_dashboard/static/src/xml/inventory_dashboard_body.xml",
            "odoo_overview_dashboard/static/src/js/overview/inventory_dashboard_body.js",
            "odoo_overview_dashboard/static/src/xml/overview_shell.xml",
            "odoo_overview_dashboard/static/src/js/overview/overview_shell.js",
            "odoo_overview_dashboard/static/src/scss/sales_overview.scss",
        ],
    },
    "installable": True,
    "application": True,
}
